# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'amz_product_details.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_amzProductDetails(object):
    def setupUi(self, amzProductDetails):
        amzProductDetails.setObjectName("amzProductDetails")
        amzProductDetails.resize(696, 248)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(amzProductDetails.sizePolicy().hasHeightForWidth())
        amzProductDetails.setSizePolicy(sizePolicy)
        amzProductDetails.setMinimumSize(QtCore.QSize(650, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(amzProductDetails)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(amzProductDetails)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(amzProductDetails)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.titleLine = QtWidgets.QLineEdit(amzProductDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLine.sizePolicy().hasHeightForWidth())
        self.titleLine.setSizePolicy(sizePolicy)
        self.titleLine.setReadOnly(True)
        self.titleLine.setObjectName("titleLine")
        self.gridLayout_2.addWidget(self.titleLine, 0, 1, 1, 4)
        self.openUPCLookupBtn = QtWidgets.QPushButton(amzProductDetails)
        self.openUPCLookupBtn.setObjectName("openUPCLookupBtn")
        self.gridLayout_2.addWidget(self.openUPCLookupBtn, 4, 4, 1, 1)
        self.openGoogleBtn = QtWidgets.QPushButton(amzProductDetails)
        self.openGoogleBtn.setObjectName("openGoogleBtn")
        self.gridLayout_2.addWidget(self.openGoogleBtn, 2, 4, 1, 1)
        self.openCamelBtn = QtWidgets.QPushButton(amzProductDetails)
        self.openCamelBtn.setObjectName("openCamelBtn")
        self.gridLayout_2.addWidget(self.openCamelBtn, 3, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(amzProductDetails)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.brandLine = QtWidgets.QLineEdit(amzProductDetails)
        self.brandLine.setReadOnly(True)
        self.brandLine.setObjectName("brandLine")
        self.gridLayout_2.addWidget(self.brandLine, 1, 1, 1, 1)
        self.openUrlBtn = QtWidgets.QPushButton(amzProductDetails)
        self.openUrlBtn.setObjectName("openUrlBtn")
        self.gridLayout_2.addWidget(self.openUrlBtn, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(amzProductDetails)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(amzProductDetails)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.salesRankLine = QtWidgets.QSpinBox(amzProductDetails)
        self.salesRankLine.setReadOnly(True)
        self.salesRankLine.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.salesRankLine.setProperty("showGroupSeparator", True)
        self.salesRankLine.setMaximum(999999999)
        self.salesRankLine.setProperty("value", 0)
        self.salesRankLine.setObjectName("salesRankLine")
        self.gridLayout_2.addWidget(self.salesRankLine, 4, 3, 1, 1)
        self.quantityBox = QtWidgets.QSpinBox(amzProductDetails)
        self.quantityBox.setReadOnly(True)
        self.quantityBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.quantityBox.setProperty("showGroupSeparator", True)
        self.quantityBox.setObjectName("quantityBox")
        self.gridLayout_2.addWidget(self.quantityBox, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(amzProductDetails)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(amzProductDetails)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 2, 1, 1)
        self.upcLine = QtWidgets.QLineEdit(amzProductDetails)
        self.upcLine.setReadOnly(True)
        self.upcLine.setObjectName("upcLine")
        self.gridLayout_2.addWidget(self.upcLine, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(amzProductDetails)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.modelLine = QtWidgets.QLineEdit(amzProductDetails)
        self.modelLine.setReadOnly(True)
        self.modelLine.setObjectName("modelLine")
        self.gridLayout_2.addWidget(self.modelLine, 2, 1, 1, 1)
        self.primeLine = QtWidgets.QLineEdit(amzProductDetails)
        self.primeLine.setReadOnly(True)
        self.primeLine.setObjectName("primeLine")
        self.gridLayout_2.addWidget(self.primeLine, 5, 3, 1, 1)
        self.categoryLine = QtWidgets.QLineEdit(amzProductDetails)
        self.categoryLine.setReadOnly(True)
        self.categoryLine.setObjectName("categoryLine")
        self.gridLayout_2.addWidget(self.categoryLine, 3, 3, 1, 1)
        self.offersBox = QtWidgets.QSpinBox(amzProductDetails)
        self.offersBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.offersBox.setProperty("showGroupSeparator", True)
        self.offersBox.setObjectName("offersBox")
        self.gridLayout_2.addWidget(self.offersBox, 5, 1, 1, 1)
        self.priceBox = QtWidgets.QDoubleSpinBox(amzProductDetails)
        self.priceBox.setReadOnly(True)
        self.priceBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.priceBox.setProperty("showGroupSeparator", True)
        self.priceBox.setObjectName("priceBox")
        self.gridLayout_2.addWidget(self.priceBox, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(amzProductDetails)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(amzProductDetails)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(amzProductDetails)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 2, 1, 1)
        self.skuLine = QtWidgets.QLineEdit(amzProductDetails)
        self.skuLine.setReadOnly(True)
        self.skuLine.setObjectName("skuLine")
        self.gridLayout_2.addWidget(self.skuLine, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.watchCheck = QtWidgets.QCheckBox(amzProductDetails)
        self.watchCheck.setObjectName("watchCheck")
        self.horizontalLayout.addWidget(self.watchCheck)
        self.watchPeriod = QtWidgets.QDoubleSpinBox(amzProductDetails)
        self.watchPeriod.setPrefix("")
        self.watchPeriod.setDecimals(1)
        self.watchPeriod.setMinimum(0.5)
        self.watchPeriod.setMaximum(24.0)
        self.watchPeriod.setSingleStep(0.5)
        self.watchPeriod.setProperty("value", 1.0)
        self.watchPeriod.setObjectName("watchPeriod")
        self.horizontalLayout.addWidget(self.watchPeriod)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(amzProductDetails)
        QtCore.QMetaObject.connectSlotsByName(amzProductDetails)

    def retranslateUi(self, amzProductDetails):
        _translate = QtCore.QCoreApplication.translate
        amzProductDetails.setWindowTitle(_translate("amzProductDetails", "Form"))
        self.label_5.setText(_translate("amzProductDetails", "UPC:"))
        self.label_3.setText(_translate("amzProductDetails", "Model:"))
        self.openUPCLookupBtn.setText(_translate("amzProductDetails", "UPC Lookup..."))
        self.openGoogleBtn.setText(_translate("amzProductDetails", "Google..."))
        self.openCamelBtn.setText(_translate("amzProductDetails", "CamelCamelCamel..."))
        self.label_2.setText(_translate("amzProductDetails", "Brand:"))
        self.openUrlBtn.setText(_translate("amzProductDetails", "Amazon..."))
        self.label.setText(_translate("amzProductDetails", "Title:"))
        self.label_8.setText(_translate("amzProductDetails", "Price:"))
        self.label_9.setText(_translate("amzProductDetails", "Quantity:"))
        self.label_7.setText(_translate("amzProductDetails", "Sales rank:"))
        self.label_4.setText(_translate("amzProductDetails", "ASIN:"))
        self.priceBox.setPrefix(_translate("amzProductDetails", "$"))
        self.label_10.setText(_translate("amzProductDetails", "Offers:"))
        self.label_11.setText(_translate("amzProductDetails", "Prime:"))
        self.label_6.setText(_translate("amzProductDetails", "Category:"))
        self.watchCheck.setText(_translate("amzProductDetails", "Watch:"))
        self.watchPeriod.setSuffix(_translate("amzProductDetails", " hr"))

