# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finamazonmatches_params.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_listMatchingProductsParams(object):
    def setupUi(self, listMatchingProductsParams):
        listMatchingProductsParams.setObjectName("listMatchingProductsParams")
        listMatchingProductsParams.resize(415, 169)
        self.verticalLayout = QtWidgets.QVBoxLayout(listMatchingProductsParams)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(listMatchingProductsParams)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.listNamesBox = QtWidgets.QComboBox(listMatchingProductsParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listNamesBox.sizePolicy().hasHeightForWidth())
        self.listNamesBox.setSizePolicy(sizePolicy)
        self.listNamesBox.setEditable(True)
        self.listNamesBox.setObjectName("listNamesBox")
        self.horizontalLayout.addWidget(self.listNamesBox)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 2)
        self.marginBox = QtWidgets.QSpinBox(listMatchingProductsParams)
        self.marginBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.marginBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.marginBox.setMaximum(999)
        self.marginBox.setProperty("value", 30)
        self.marginBox.setObjectName("marginBox")
        self.gridLayout.addWidget(self.marginBox, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(listMatchingProductsParams)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(listMatchingProductsParams)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(listMatchingProductsParams)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.confidenceBox = QtWidgets.QSpinBox(listMatchingProductsParams)
        self.confidenceBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confidenceBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.confidenceBox.setMaximum(100)
        self.confidenceBox.setProperty("value", 75)
        self.confidenceBox.setObjectName("confidenceBox")
        self.gridLayout.addWidget(self.confidenceBox, 0, 2, 1, 1)
        self.salesRankBox = QtWidgets.QSpinBox(listMatchingProductsParams)
        self.salesRankBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.salesRankBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.salesRankBox.setProperty("showGroupSeparator", True)
        self.salesRankBox.setMinimum(1)
        self.salesRankBox.setMaximum(9999999)
        self.salesRankBox.setProperty("value", 300000)
        self.salesRankBox.setObjectName("salesRankBox")
        self.gridLayout.addWidget(self.salesRankBox, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(listMatchingProductsParams)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(listMatchingProductsParams)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.testMarginsCheck = QtWidgets.QCheckBox(listMatchingProductsParams)
        self.testMarginsCheck.setObjectName("testMarginsCheck")
        self.horizontalLayout_2.addWidget(self.testMarginsCheck)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(listMatchingProductsParams)
        QtCore.QMetaObject.connectSlotsByName(listMatchingProductsParams)

    def retranslateUi(self, listMatchingProductsParams):
        _translate = QtCore.QCoreApplication.translate
        listMatchingProductsParams.setWindowTitle(_translate("listMatchingProductsParams", "Form"))
        self.label_7.setText(_translate("listMatchingProductsParams", "List:"))
        self.marginBox.setSuffix(_translate("listMatchingProductsParams", "%"))
        self.label_6.setText(_translate("listMatchingProductsParams", "Margin at least"))
        self.label.setText(_translate("listMatchingProductsParams", "Create link if:"))
        self.label_4.setText(_translate("listMatchingProductsParams", "Sales rank less than "))
        self.confidenceBox.setSuffix(_translate("listMatchingProductsParams", "%"))
        self.label_2.setText(_translate("listMatchingProductsParams", "Match confidence at least "))
        self.label_3.setText(_translate("listMatchingProductsParams", "Test margins if:"))
        self.testMarginsCheck.setText(_translate("listMatchingProductsParams", "Add to list if:"))

