# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importcsv.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImportCSV(object):
    def setupUi(self, ImportCSV):
        ImportCSV.setObjectName("ImportCSV")
        ImportCSV.setWindowModality(QtCore.Qt.WindowModal)
        ImportCSV.resize(586, 158)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImportCSV.sizePolicy().hasHeightForWidth())
        ImportCSV.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportCSV)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ImportCSV)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileLine = QtWidgets.QLineEdit(ImportCSV)
        self.fileLine.setObjectName("fileLine")
        self.horizontalLayout_2.addWidget(self.fileLine)
        self.fileButton = QtWidgets.QToolButton(ImportCSV)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_2.addWidget(self.fileButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(ImportCSV)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startBox = QtWidgets.QSpinBox(ImportCSV)
        self.startBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startBox.setAccelerated(True)
        self.startBox.setProperty("showGroupSeparator", True)
        self.startBox.setMaximum(999999)
        self.startBox.setObjectName("startBox")
        self.horizontalLayout.addWidget(self.startBox)
        self.label_3 = QtWidgets.QLabel(ImportCSV)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.endBox = QtWidgets.QSpinBox(ImportCSV)
        self.endBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endBox.setAccelerated(True)
        self.endBox.setProperty("showGroupSeparator", True)
        self.endBox.setMaximum(999999)
        self.endBox.setObjectName("endBox")
        self.horizontalLayout.addWidget(self.endBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(ImportCSV)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.vendorBox = QtWidgets.QComboBox(ImportCSV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vendorBox.sizePolicy().hasHeightForWidth())
        self.vendorBox.setSizePolicy(sizePolicy)
        self.vendorBox.setEditable(True)
        self.vendorBox.setObjectName("vendorBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vendorBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statusLabel = QtWidgets.QLabel(ImportCSV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setText("")
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_3.addWidget(self.statusLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImportCSV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ImportCSV)
        self.buttonBox.accepted.connect(ImportCSV.accept)
        self.buttonBox.rejected.connect(ImportCSV.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportCSV)

    def retranslateUi(self, ImportCSV):
        _translate = QtCore.QCoreApplication.translate
        ImportCSV.setWindowTitle(_translate("ImportCSV", "Import from CSV"))
        self.label.setText(_translate("ImportCSV", "From file:"))
        self.fileButton.setText(_translate("ImportCSV", "..."))
        self.label_2.setText(_translate("ImportCSV", "Import rows:"))
        self.label_3.setText(_translate("ImportCSV", "to"))
        self.label_4.setText(_translate("ImportCSV", "Into source:"))

