# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operationsview.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_operationsView(object):
    def setupUi(self, operationsView):
        operationsView.setObjectName("operationsView")
        operationsView.resize(836, 608)
        self.verticalLayout = QtWidgets.QVBoxLayout(operationsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statusMsgList = QtWidgets.QListWidget(operationsView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.statusMsgList.sizePolicy().hasHeightForWidth())
        self.statusMsgList.setSizePolicy(sizePolicy)
        self.statusMsgList.setObjectName("statusMsgList")
        self.verticalLayout.addWidget(self.statusMsgList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(operationsView)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pendingBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pendingBox.sizePolicy().hasHeightForWidth())
        self.pendingBox.setSizePolicy(sizePolicy)
        self.pendingBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pendingBox.setReadOnly(True)
        self.pendingBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pendingBox.setProperty("showGroupSeparator", True)
        self.pendingBox.setMaximum(9999999)
        self.pendingBox.setObjectName("pendingBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pendingBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.completedBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completedBox.sizePolicy().hasHeightForWidth())
        self.completedBox.setSizePolicy(sizePolicy)
        self.completedBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.completedBox.setReadOnly(True)
        self.completedBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.completedBox.setProperty("showGroupSeparator", True)
        self.completedBox.setMaximum(9999999)
        self.completedBox.setObjectName("completedBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.completedBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.totalBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalBox.sizePolicy().hasHeightForWidth())
        self.totalBox.setSizePolicy(sizePolicy)
        self.totalBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalBox.setReadOnly(True)
        self.totalBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.totalBox.setProperty("showGroupSeparator", True)
        self.totalBox.setMaximum(9999999)
        self.totalBox.setObjectName("totalBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.totalBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.timeRemaining = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeRemaining.sizePolicy().hasHeightForWidth())
        self.timeRemaining.setSizePolicy(sizePolicy)
        self.timeRemaining.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeRemaining.setReadOnly(True)
        self.timeRemaining.setObjectName("timeRemaining")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeRemaining)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(operationsView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.actionStart = QtWidgets.QAction(operationsView)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("148705-essential-collection/png/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStart.setIcon(icon)
        self.actionStart.setObjectName("actionStart")
        self.actionPause = QtWidgets.QAction(operationsView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("148705-essential-collection/png/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPause.setIcon(icon1)
        self.actionPause.setObjectName("actionPause")
        self.actionNew_batch = QtWidgets.QAction(operationsView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("148705-essential-collection/png/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew_batch.setIcon(icon2)
        self.actionNew_batch.setObjectName("actionNew_batch")

        self.retranslateUi(operationsView)
        QtCore.QMetaObject.connectSlotsByName(operationsView)

    def retranslateUi(self, operationsView):
        _translate = QtCore.QCoreApplication.translate
        operationsView.setWindowTitle(_translate("operationsView", "Form"))
        self.groupBox.setTitle(_translate("operationsView", "Statistics:"))
        self.label.setText(_translate("operationsView", "Pending:"))
        self.label_2.setText(_translate("operationsView", "Completed:"))
        self.label_3.setText(_translate("operationsView", "Total:"))
        self.label_4.setText(_translate("operationsView", "Est. time remaining:"))
        self.groupBox_2.setTitle(_translate("operationsView", "Amazon request quotas:"))
        self.actionStart.setText(_translate("operationsView", "Start"))
        self.actionStart.setToolTip(_translate("operationsView", "Start"))
        self.actionPause.setText(_translate("operationsView", "Pause"))
        self.actionPause.setToolTip(_translate("operationsView", "Pause"))
        self.actionNew_batch.setText(_translate("operationsView", "New batch..."))
        self.actionNew_batch.setToolTip(_translate("operationsView", "New batch"))

