# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operationsview.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_operationsView(object):
    def setupUi(self, operationsView):
        operationsView.setObjectName("operationsView")
        operationsView.resize(836, 608)
        self.verticalLayout = QtWidgets.QVBoxLayout(operationsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageList = QtWidgets.QListWidget(operationsView)
        self.messageList.setAlternatingRowColors(True)
        self.messageList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.messageList.setObjectName("messageList")
        self.verticalLayout.addWidget(self.messageList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(operationsView)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.timeRemaining = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeRemaining.sizePolicy().hasHeightForWidth())
        self.timeRemaining.setSizePolicy(sizePolicy)
        self.timeRemaining.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeRemaining.setReadOnly(True)
        self.timeRemaining.setObjectName("timeRemaining")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeRemaining)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pendingBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pendingBox.sizePolicy().hasHeightForWidth())
        self.pendingBox.setSizePolicy(sizePolicy)
        self.pendingBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pendingBox.setReadOnly(True)
        self.pendingBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pendingBox.setProperty("showGroupSeparator", True)
        self.pendingBox.setMaximum(9999999)
        self.pendingBox.setObjectName("pendingBox")
        self.horizontalLayout_2.addWidget(self.pendingBox)
        self.clearPendingBtn = QtWidgets.QToolButton(self.groupBox)
        self.clearPendingBtn.setObjectName("clearPendingBtn")
        self.horizontalLayout_2.addWidget(self.clearPendingBtn)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.completedBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completedBox.sizePolicy().hasHeightForWidth())
        self.completedBox.setSizePolicy(sizePolicy)
        self.completedBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.completedBox.setReadOnly(True)
        self.completedBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.completedBox.setProperty("showGroupSeparator", True)
        self.completedBox.setMaximum(9999999)
        self.completedBox.setObjectName("completedBox")
        self.horizontalLayout_3.addWidget(self.completedBox)
        self.clearCompletedBtn = QtWidgets.QToolButton(self.groupBox)
        self.clearCompletedBtn.setObjectName("clearCompletedBtn")
        self.horizontalLayout_3.addWidget(self.clearCompletedBtn)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.errorBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorBox.sizePolicy().hasHeightForWidth())
        self.errorBox.setSizePolicy(sizePolicy)
        self.errorBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.errorBox.setReadOnly(True)
        self.errorBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.errorBox.setProperty("showGroupSeparator", True)
        self.errorBox.setMaximum(9999999)
        self.errorBox.setObjectName("errorBox")
        self.horizontalLayout_4.addWidget(self.errorBox)
        self.clearErrorsBtn = QtWidgets.QToolButton(self.groupBox)
        self.clearErrorsBtn.setObjectName("clearErrorsBtn")
        self.horizontalLayout_4.addWidget(self.clearErrorsBtn)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(operationsView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.actionStart = QtWidgets.QAction(operationsView)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStart.setIcon(icon)
        self.actionStart.setObjectName("actionStart")
        self.actionPause = QtWidgets.QAction(operationsView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPause.setIcon(icon1)
        self.actionPause.setObjectName("actionPause")
        self.actionNew_batch = QtWidgets.QAction(operationsView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/operations.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew_batch.setIcon(icon2)
        self.actionNew_batch.setObjectName("actionNew_batch")

        self.retranslateUi(operationsView)
        QtCore.QMetaObject.connectSlotsByName(operationsView)

    def retranslateUi(self, operationsView):
        _translate = QtCore.QCoreApplication.translate
        operationsView.setWindowTitle(_translate("operationsView", "Form"))
        self.groupBox.setTitle(_translate("operationsView", "Statistics:"))
        self.label.setText(_translate("operationsView", "Pending:"))
        self.label_2.setText(_translate("operationsView", "Completed:"))
        self.label_3.setText(_translate("operationsView", "Errors:"))
        self.label_4.setText(_translate("operationsView", "Est. time remaining:"))
        self.clearPendingBtn.setText(_translate("operationsView", "Clear"))
        self.clearCompletedBtn.setText(_translate("operationsView", "Clear"))
        self.clearErrorsBtn.setText(_translate("operationsView", "Clear"))
        self.groupBox_2.setTitle(_translate("operationsView", "Amazon request quotas:"))
        self.actionStart.setText(_translate("operationsView", "Start"))
        self.actionStart.setToolTip(_translate("operationsView", "Start"))
        self.actionPause.setText(_translate("operationsView", "Pause"))
        self.actionPause.setToolTip(_translate("operationsView", "Pause"))
        self.actionNew_batch.setText(_translate("operationsView", "New batch..."))
        self.actionNew_batch.setToolTip(_translate("operationsView", "New batch"))

