# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vnd_product_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_vndProductDialog(object):
    def setupUi(self, vndProductDialog):
        vndProductDialog.setObjectName("vndProductDialog")
        vndProductDialog.resize(541, 244)
        self.verticalLayout = QtWidgets.QVBoxLayout(vndProductDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(vndProductDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.titleLine = QtWidgets.QLineEdit(vndProductDialog)
        self.titleLine.setObjectName("titleLine")
        self.gridLayout.addWidget(self.titleLine, 0, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(vndProductDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.urlLine = QtWidgets.QLineEdit(vndProductDialog)
        self.urlLine.setObjectName("urlLine")
        self.gridLayout.addWidget(self.urlLine, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(vndProductDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.vendorBox = QtWidgets.QComboBox(vndProductDialog)
        self.vendorBox.setEditable(True)
        self.vendorBox.setObjectName("vendorBox")
        self.gridLayout.addWidget(self.vendorBox, 2, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(vndProductDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.brandLine = QtWidgets.QLineEdit(vndProductDialog)
        self.brandLine.setObjectName("brandLine")
        self.gridLayout.addWidget(self.brandLine, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(vndProductDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.skuLine = QtWidgets.QLineEdit(vndProductDialog)
        self.skuLine.setObjectName("skuLine")
        self.gridLayout.addWidget(self.skuLine, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(vndProductDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.modelLine = QtWidgets.QLineEdit(vndProductDialog)
        self.modelLine.setObjectName("modelLine")
        self.gridLayout.addWidget(self.modelLine, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(vndProductDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 2, 1, 1)
        self.upcLine = QtWidgets.QLineEdit(vndProductDialog)
        self.upcLine.setObjectName("upcLine")
        self.gridLayout.addWidget(self.upcLine, 4, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(vndProductDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.priceBox = QtWidgets.QDoubleSpinBox(vndProductDialog)
        self.priceBox.setMaximum(999999.0)
        self.priceBox.setObjectName("priceBox")
        self.gridLayout.addWidget(self.priceBox, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(vndProductDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.quantityBox = QtWidgets.QSpinBox(vndProductDialog)
        self.quantityBox.setMaximum(999999)
        self.quantityBox.setObjectName("quantityBox")
        self.gridLayout.addWidget(self.quantityBox, 5, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(vndProductDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(vndProductDialog)
        self.buttonBox.accepted.connect(vndProductDialog.accept)
        self.buttonBox.rejected.connect(vndProductDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(vndProductDialog)

    def retranslateUi(self, vndProductDialog):
        _translate = QtCore.QCoreApplication.translate
        vndProductDialog.setWindowTitle(_translate("vndProductDialog", "Dialog"))
        self.label.setText(_translate("vndProductDialog", "Title:"))
        self.label_3.setText(_translate("vndProductDialog", "URL:"))
        self.label_2.setText(_translate("vndProductDialog", "Vendor:"))
        self.label_4.setText(_translate("vndProductDialog", "Brand:"))
        self.label_6.setText(_translate("vndProductDialog", "SKU:"))
        self.label_5.setText(_translate("vndProductDialog", "Model:"))
        self.label_7.setText(_translate("vndProductDialog", "UPC:"))
        self.label_8.setText(_translate("vndProductDialog", "Price:"))
        self.priceBox.setPrefix(_translate("vndProductDialog", "$"))
        self.label_9.setText(_translate("vndProductDialog", "Quantity:"))

