# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vnd_listing_details.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_vendorListingDetails(object):
    def setupUi(self, vendorListingDetails):
        vendorListingDetails.setObjectName("vendorListingDetails")
        vendorListingDetails.resize(590, 286)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(vendorListingDetails.sizePolicy().hasHeightForWidth())
        vendorListingDetails.setSizePolicy(sizePolicy)
        vendorListingDetails.setMinimumSize(QtCore.QSize(590, 0))
        self.gridLayout = QtWidgets.QGridLayout(vendorListingDetails)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.openGoogleBtn = QtWidgets.QPushButton(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGoogleBtn.sizePolicy().hasHeightForWidth())
        self.openGoogleBtn.setSizePolicy(sizePolicy)
        self.openGoogleBtn.setObjectName("openGoogleBtn")
        self.gridLayout_2.addWidget(self.openGoogleBtn, 3, 4, 1, 1)
        self.brandLine = QtWidgets.QLineEdit(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brandLine.sizePolicy().hasHeightForWidth())
        self.brandLine.setSizePolicy(sizePolicy)
        self.brandLine.setReadOnly(True)
        self.brandLine.setObjectName("brandLine")
        self.gridLayout_2.addWidget(self.brandLine, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.titleLine = QtWidgets.QLineEdit(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLine.sizePolicy().hasHeightForWidth())
        self.titleLine.setSizePolicy(sizePolicy)
        self.titleLine.setMinimumSize(QtCore.QSize(513, 0))
        self.titleLine.setReadOnly(True)
        self.titleLine.setObjectName("titleLine")
        self.gridLayout_2.addWidget(self.titleLine, 0, 1, 1, 4)
        self.label = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.priceBox = QtWidgets.QDoubleSpinBox(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceBox.sizePolicy().hasHeightForWidth())
        self.priceBox.setSizePolicy(sizePolicy)
        self.priceBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.priceBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.priceBox.setMaximum(999999.0)
        self.priceBox.setObjectName("priceBox")
        self.gridLayout_2.addWidget(self.priceBox, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.updatedLine = QtWidgets.QLineEdit(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updatedLine.sizePolicy().hasHeightForWidth())
        self.updatedLine.setSizePolicy(sizePolicy)
        self.updatedLine.setReadOnly(True)
        self.updatedLine.setObjectName("updatedLine")
        self.gridLayout_2.addWidget(self.updatedLine, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 2, 1, 1)
        self.upcLine = QtWidgets.QLineEdit(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upcLine.sizePolicy().hasHeightForWidth())
        self.upcLine.setSizePolicy(sizePolicy)
        self.upcLine.setReadOnly(True)
        self.upcLine.setObjectName("upcLine")
        self.gridLayout_2.addWidget(self.upcLine, 4, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 6, 2, 1, 1)
        self.vendorLine = QtWidgets.QLineEdit(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vendorLine.sizePolicy().hasHeightForWidth())
        self.vendorLine.setSizePolicy(sizePolicy)
        self.vendorLine.setReadOnly(True)
        self.vendorLine.setObjectName("vendorLine")
        self.gridLayout_2.addWidget(self.vendorLine, 1, 1, 1, 3)
        self.openVendorBtn = QtWidgets.QPushButton(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openVendorBtn.sizePolicy().hasHeightForWidth())
        self.openVendorBtn.setSizePolicy(sizePolicy)
        self.openVendorBtn.setObjectName("openVendorBtn")
        self.gridLayout_2.addWidget(self.openVendorBtn, 1, 4, 1, 1)
        self.urlLine = QtWidgets.QLineEdit(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLine.sizePolicy().hasHeightForWidth())
        self.urlLine.setSizePolicy(sizePolicy)
        self.urlLine.setReadOnly(True)
        self.urlLine.setObjectName("urlLine")
        self.gridLayout_2.addWidget(self.urlLine, 2, 1, 1, 3)
        self.label_19 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 7, 0, 1, 1)
        self.openUPCLookupBtn = QtWidgets.QPushButton(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openUPCLookupBtn.sizePolicy().hasHeightForWidth())
        self.openUPCLookupBtn.setSizePolicy(sizePolicy)
        self.openUPCLookupBtn.setObjectName("openUPCLookupBtn")
        self.gridLayout_2.addWidget(self.openUPCLookupBtn, 4, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.openUrlBtn = QtWidgets.QPushButton(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openUrlBtn.sizePolicy().hasHeightForWidth())
        self.openUrlBtn.setSizePolicy(sizePolicy)
        self.openUrlBtn.setObjectName("openUrlBtn")
        self.gridLayout_2.addWidget(self.openUrlBtn, 2, 4, 1, 1)
        self.quantityBox = QtWidgets.QSpinBox(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantityBox.sizePolicy().hasHeightForWidth())
        self.quantityBox.setSizePolicy(sizePolicy)
        self.quantityBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.quantityBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.quantityBox.setObjectName("quantityBox")
        self.gridLayout_2.addWidget(self.quantityBox, 6, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.modelLine = QtWidgets.QLineEdit(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLine.sizePolicy().hasHeightForWidth())
        self.modelLine.setSizePolicy(sizePolicy)
        self.modelLine.setReadOnly(True)
        self.modelLine.setObjectName("modelLine")
        self.gridLayout_2.addWidget(self.modelLine, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        self.skuLine = QtWidgets.QLineEdit(vendorListingDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skuLine.sizePolicy().hasHeightForWidth())
        self.skuLine.setSizePolicy(sizePolicy)
        self.skuLine.setReadOnly(True)
        self.skuLine.setObjectName("skuLine")
        self.gridLayout_2.addWidget(self.skuLine, 3, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.deleteListingBtn = QtWidgets.QPushButton(vendorListingDetails)
        self.deleteListingBtn.setObjectName("deleteListingBtn")
        self.horizontalLayout_4.addWidget(self.deleteListingBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(vendorListingDetails)
        QtCore.QMetaObject.connectSlotsByName(vendorListingDetails)

    def retranslateUi(self, vendorListingDetails):
        _translate = QtCore.QCoreApplication.translate
        vendorListingDetails.setWindowTitle(_translate("vendorListingDetails", "Form"))
        self.openGoogleBtn.setText(_translate("vendorListingDetails", "Google..."))
        self.label_2.setText(_translate("vendorListingDetails", "Brand:"))
        self.label.setText(_translate("vendorListingDetails", "Title:"))
        self.priceBox.setPrefix(_translate("vendorListingDetails", "$"))
        self.label_6.setText(_translate("vendorListingDetails", "URL:"))
        self.label_5.setText(_translate("vendorListingDetails", "UPC:"))
        self.label_18.setText(_translate("vendorListingDetails", "Price:"))
        self.label_17.setText(_translate("vendorListingDetails", "Quantity:"))
        self.openVendorBtn.setText(_translate("vendorListingDetails", "Vendor..."))
        self.label_19.setText(_translate("vendorListingDetails", "Updated:"))
        self.openUPCLookupBtn.setText(_translate("vendorListingDetails", "UPC Lookup..."))
        self.label_7.setText(_translate("vendorListingDetails", "Vendor:"))
        self.openUrlBtn.setText(_translate("vendorListingDetails", "Open..."))
        self.label_3.setText(_translate("vendorListingDetails", "Model:"))
        self.label_4.setText(_translate("vendorListingDetails", "SKU:"))
        self.deleteListingBtn.setText(_translate("vendorListingDetails", "Delete Listing"))

